using System.Collections.Generic;
using Terraria.ID;

namespace Permabuffs
{
    public static class Potions
    {
        public static readonly Dictionary<string, int> BuffMap = new(StringComparer.OrdinalIgnoreCase)
        {
            // Potions
            { "ironskin potion", BuffID.Ironskin },
            { "regeneration potion", BuffID.Regeneration },
            { "swiftness potion", BuffID.Swiftness },
            { "endurance potion", BuffID.Endurance },
            { "obsidian skin potion", BuffID.ObsidianSkin },
            { "mining potion", BuffID.Mining },
            { "heartreach potion", BuffID.Heartreach },
            { "spelunker potion", BuffID.Spelunker },
            { "hunter potion", BuffID.Hunter },
            { "night owl potion", BuffID.NightOwl },
            { "shine potion", BuffID.Shine },
            { "thorns potion", BuffID.Thorns },
            { "mana regeneration potion", BuffID.ManaRegeneration },
            { "magic power potion", BuffID.MagicPower },
            { "featherfall potion", BuffID.Featherfall },
            { "archery potion", BuffID.Archery },
            { "gills potion", BuffID.Gills },
            { "calming potion", BuffID.Calm },
            { "wrath potion", BuffID.Wrath },
            { "rage potion", BuffID.Rage },
            { "inferno potion", BuffID.Inferno },
            { "lifeforce potion", BuffID.Lifeforce },
            { "titan potion", BuffID.Titan },
            { "summoning potion", BuffID.Summoning },
            { "builder potion", BuffID.Builder },
            { "battle potion", BuffID.Battle },
            { "dangersense potion", BuffID.Dangersense },
            { "gravitation potion", BuffID.Gravitation },
            { "ammo reservation potion", BuffID.AmmoReservation },
            { "warmth potion", BuffID.Warmth },
            { "fishing potion", BuffID.Fishing },
            { "crate potion", BuffID.Crate },
            { "sonar potion", BuffID.Sonar },
            { "invisibility potion", BuffID.Invisibility },
            { "teleportation potion", BuffID.Teleportation },
            { "gender change potion", BuffID.GenderChange },
            { "lifeforce potion", BuffID.Lifeforce },
            { "greater luck potion", BuffID.Luck },
            { "luck potion", BuffID.Luck },
            { "lesser luck potion", BuffID.Luck },

            // Flasks
            { "flask of cursed flames", BuffID.WeaponImbueCursedFlames },
            { "flask of fire", BuffID.WeaponImbueFire },
            { "flask of gold", BuffID.WeaponImbueGold },
            { "flask of ichor", BuffID.WeaponImbueIchor },
            { "flask of nanites", BuffID.WeaponImbueNanites },
            { "flask of party", BuffID.WeaponImbueConfetti },
            { "flask of poison", BuffID.WeaponImbueVenom },

            // Drinks (Tipsy)
            { "ale", BuffID.Tipsy },
            { "sake", BuffID.Tipsy },

            // Well‑Fed (BuffID.WellFed)
            { "apple", BuffID.WellFed },
            { "apple juice", BuffID.WellFed },
            { "bloody moscato", BuffID.WellFed },
            { "bunny stew", BuffID.WellFed },
            { "cooked fish", BuffID.WellFed },
            { "frozen banana daiquiri", BuffID.WellFed },
            { "fruit juice", BuffID.WellFed },
            { "fruit salad", BuffID.WellFed },
            { "grilled squirrel", BuffID.WellFed },
            { "lemonade", BuffID.WellFed },
            { "peach sangria", BuffID.WellFed },
            { "roasted bird", BuffID.WellFed },
            { "smoothie of darkness", BuffID.WellFed },
            { "tropical smoothie", BuffID.WellFed },
            { "teacup", BuffID.WellFed },
            { "apricot", BuffID.WellFed },
            { "banana", BuffID.WellFed },
            { "blackcurrant", BuffID.WellFed },
            { "blood orange", BuffID.WellFed },
            { "cherry", BuffID.WellFed },
            { "coconut", BuffID.WellFed },
            { "elderberry", BuffID.WellFed },
            { "grapefruit", BuffID.WellFed },
            { "lemon", BuffID.WellFed },
            { "mango", BuffID.WellFed },
            { "peach", BuffID.WellFed },
            { "pineapple", BuffID.WellFed },
            { "plum", BuffID.WellFed },
            { "rambutan", BuffID.WellFed },
            { "carton of milk", BuffID.WellFed },
            { "potato chips", BuffID.WellFed },
            { "shucked oyster", BuffID.WellFed },
            { "marshmallow", BuffID.WellFed },

            // Plenty Satisfied (BuffID.WellFed2 or 206 if mapping to 206)
            { "grub soup", BuffID.WellFed },
            { "bowl of soup", BuffID.WellFed },
            { "cooked shrimp", BuffID.WellFed2 },
            { "pumpkin pie", BuffID.WellFed },
            { "sashimi", BuffID.WellFed },
            { "escargot", BuffID.WellFed },
            { "lobster tail", BuffID.WellFed2 },
            { "prismatic punch", BuffID.WellFed2 },
            { "roasted duck", BuffID.WellFed2 },
            { "sauteed frog legs", BuffID.WellFed },
            { "pho", BuffID.WellFed2 },
            { "pad thai", BuffID.WellFed },
            { "dragon fruit", BuffID.WellFed },
            { "star fruit", BuffID.WellFed },
            { "banana split", BuffID.WellFed2 },
            { "chicken nugget", BuffID.WellFed2 },
            { "chocolate chip cookie", BuffID.WellFed },
            { "coffee", BuffID.WellFed },
            { "cream soda", BuffID.WellFed },
            { "fried egg", BuffID.WellFed },
            { "fries", BuffID.WellFed2 },
            { "grapes", BuffID.WellFed },
            { "hotdog", BuffID.WellFed2 },
            { "ice cream", BuffID.WellFed2 },
            { "nachos", BuffID.WellFed2 },

            // Exquisitely Stuffed (BuffID.WellFed3)
            { "golden delight", BuffID.WellFed3 },
            { "grape juice", BuffID.WellFed3 },
            { "seafood dinner", BuffID.WellFed3 },
            { "bacon", BuffID.WellFed3 },
            { "christmas pudding", BuffID.WellFed3 },
            { "gingerbread cookie", BuffID.WellFed3 },
            { "sugar cookie", BuffID.WellFed3 },
            { "apple pie", BuffID.WellFed3 },
            { "bbq ribs", BuffID.WellFed3 },
            { "burger", BuffID.WellFed3 },
            { "milkshake", BuffID.WellFed3 },
            { "pizza", BuffID.WellFed3 },
            { "spaghetti", BuffID.WellFed3 },
            { "steak", BuffID.WellFed3 },
            { "stuffing", BuffID.WellFed3 },
            { "donut", BuffID.WellFed },
            { "frosted donut", BuffID.WellFed },
            { "frosted cake", BuffID.WellFed },
            { "cheeseburger", BuffID.WellFed2 },
            { "cheese pizza", BuffID.WellFed2 },
            { "candy apple", BuffID.WellFed },
            { "candy cane", BuffID.WellFed },
            { "sundae", BuffID.WellFed2 },
            { "mushroom stew", BuffID.WellFed },
            { "meatball", BuffID.WellFed },
            { "spicy pepper", BuffID.WellFed },
            { "strange brew", BuffID.WellFed },
            { "turkey dinner", BuffID.WellFed3 },
            { "carrot", BuffID.WellFed },
            { "cooked scorpion", BuffID.WellFed },
            { "scorpion stew", BuffID.WellFed3 }
        };
    }
}