name: Build Permabuffs Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - run: dotnet restore Permabuffs/Permabuffs.csproj
      - run: dotnet build Permabuffs/Permabuffs.csproj -c Release -r linux-arm64 --no-self-contained
      - run: dotnet publish Permabuffs/Permabuffs.csproj -c Release -r linux-arm64 --no-self-contained -o ./output
      - uses: actions/upload-artifact@v4
        with:
          name: Permabuffs-Plugin
          path: ./output/