name: Build Permabuffs for ARM64

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Build Permabuffs plugin
        run: dotnet build Permabuffs/Permabuffs.csproj -c Release -r linux-arm64 --no-self-contained